#
# Copyright 2020- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#
server:
  port: ${ZIPKIN_PORT}

eureka:
  instance:
    # Indicates how often (in seconds) the eureka client needs to send heartbeats to eureka server to indicate that it is still alive.
    leaseRenewalIntervalInSeconds: 60
    # Indicates the time in seconds that the eureka server waits since it received the last heartbeat before it can remove this instance from its view.
    leaseExpirationDurationInSeconds: 90
    hostname: ${DOCKER_MACHINE_IP}
  client:
    service-url:
      defaultZone: http://${DOCKER_MACHINE_IP}:${EUREKA_PORT}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: service-zipkin
  sleuth:
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false

logging:
  file: ./${spring.application.name}.log
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: DEBUG